#!/bin/bash

echo "╔══════════════════════════════════════════════════════════╗"
echo "║   🎉 STEAM MARKETPLACE - ПУБЛИЧНЫЙ ДОСТУП БЕЗ ХОСТИНГА   ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

echo "Приложение уже запущено на порту 8080 ✅"
echo ""
echo "=== ШАГ 1: УСТАНОВИТЕ CLOUDFLARE TUNNEL ==="
echo ""
echo "Скопируйте и вставьте по очереди:"
echo ""
echo "# Скачать:"
echo "wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64"
echo ""
echo "# Установить:"
echo "chmod +x cloudflared-linux-amd64"
echo "sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared"
echo ""
echo "=== ШАГ 2: ЗАПУСТИТЕ ТУННЕЛЬ ==="
echo ""
echo "После установки выполните:"
echo "cloudflared tunnel --url http://localhost:8080"
echo ""
echo "=== ШАГ 3: ПОЛУЧИТЕ ПУБЛИЧНЫЙ URL ==="
echo ""
echo "Вы увидите:"
echo "  Your tunnel: https://steam-marketplace-xxx.trycloudflare.com"
echo ""
echo "=== ШАГ 4: ТЕСТИРУЙТЕ STEAM OAUTH ==="
echo ""
echo "curl -I https://steam-marketplace-xxx.trycloudflare.com/api/auth/steam"
echo ""
echo "Ожидаемый результат:"
echo "  HTTP/2 302"
echo "  location: https://steamcommunity.com/openid/login"
echo ""
echo "=== ШАГ 5: ОТКРОЙТЕ В БРАУЗЕРЕ ==="
echo ""
echo "https://steam-marketplace-xxx.trycloudflare.com"
echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║                    ✅ БЕСПЛАТНО И РАБОТАЕТ!             ║"
echo "╚══════════════════════════════════════════════════════════╝"
